Test: randoop.jodatime.RandoopTest1.test235
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest1.test181]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest1.test181
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest0.test498]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest2.test490
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest2.test487]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest2.test487
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest2.test356]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest2.test356
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest1.test235]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest4.test259
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest4.test4]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest4.test4
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest3.test496]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest3.test496
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest3.test487]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest3.test487
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest3.test471]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest3.test471
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest3.test470]
The revealed different behavior: PASS
when executed after: []

Test: randoop.jodatime.RandoopTest3.test470
Intended behavior: FAILURE
when executed after: [randoop.jodatime.RandoopTest2.test490]
The revealed different behavior: PASS
when executed after: []

