Test: randoop.xmlsecurity.RandoopTest1.test124
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest1.test81]
The revealed different behavior: PASS
when executed after: []

Test: randoop.xmlsecurity.RandoopTest0.test213
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest0.test40]
The revealed different behavior: PASS
when executed after: []

Test: randoop.xmlsecurity.RandoopTest1.test31
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest1.test15]
The revealed different behavior: PASS
when executed after: []

Test: randoop.xmlsecurity.RandoopTest1.test13
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest0.test495]
The revealed different behavior: PASS
when executed after: []

Test: randoop.xmlsecurity.RandoopTest1.test15
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest0.test363]
The revealed different behavior: PASS
when executed after: []

Test: randoop.xmlsecurity.RandoopTest0.test408
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest0.test199]
The revealed different behavior: PASS
when executed after: []

Test: randoop.xmlsecurity.RandoopTest1.test81
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest1.test13]
The revealed different behavior: PASS
when executed after: []

Test: randoop.xmlsecurity.RandoopTest0.test495
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest0.test488]
The revealed different behavior: PASS
when executed after: []

Test: randoop.xmlsecurity.RandoopTest0.test363
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest0.test342]
The revealed different behavior: PASS
when executed after: []

Test: randoop.xmlsecurity.RandoopTest0.test342
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest0.test211]
The revealed different behavior: PASS
when executed after: []

Test: randoop.xmlsecurity.RandoopTest0.test488
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest0.test343]
The revealed different behavior: PASS
when executed after: []

Test: randoop.xmlsecurity.RandoopTest0.test343
Intended behavior: FAILURE
when executed after: [randoop.xmlsecurity.RandoopTest0.test213]
The revealed different behavior: PASS
when executed after: []

